### ISSUE TITLE
БЭМ по PNG1.html and styles1.less

### ISSUE THREAD

**Issue by honia19** [honia19/JSAnton#1]
Я ПНГ1 сделал вроде как по БЭМу посмотри пожалуйста +- так или что то категорически не верно и в styles1.less правильно прописал относительно html классов?)

**Comment by PolomkinA** [comment]
Я так понял ты уже пофиксил?

**Comment by honia19** [comment]
дофикшиваю

**Comment by honia19** [comment]
Пофиксил и запушил, посмотри если можешь)
